Include Howler.js
sorrycc/awesome-javascript pull request #744
Opened 2020-10-25 19:27 UTC by chidindu-ogbonna

This library is useful for handling audio on the web.

2020-10-25 21:22 UTC, gokaygurcan requested changes
Add new links at the end, not in the middle please.

2020-10-25 21:29 UTC, chidindu-ogbonna commented
> Add new links at the end, not in the middle please.

Okay, done.

2020-10-26 10:56 UTC, gokaygurcan approved these changes

2020-10-26 10:57 UTC, gokaygurcan commented on README.md
> +  * [Howler.js](https://github.com/goldfire/howler.js) - Javascript audio library for the modern web. This makes working with audio in JavaScript easy and reliable across all platforms.
you have an additional space in front

2020-10-26 10:58 UTC, gokaygurcan commented
If you also want to fix this, I'll wait, otherwise it doesn't break anything and we can also merge it like as is.

2024-07-20 09:50 UTC, closed without merging