docs: add G2, G2Plot
sorrycc/awesome-javascript pull request #760
Opened 2021-01-30 14:14 UTC by hustcc

- [x] add G2, G2Plot in data visualization
 - [x] update echarts repo url

2021-01-31 13:47 UTC, gokaygurcan requested changes
Thanks for updating the old link. 
Can you please move the new ones to the bottom of their block? Thanks in advance!

2021-01-31 14:17 UTC, hustcc commented
> Thanks for updating the old link.
> Can you please move the new ones to the bottom of their block? Thanks in advance!

done.

2021-02-01 11:21 UTC, gokaygurcan approved these changes

2021-02-01 11:21 UTC, gokaygurcan commented
Thanks!

2021-02-01 11:22 UTC, merged