update a bunch of links
sorrycc/awesome-javascript pull request #802
Opened 2021-12-06 21:14 UTC by nschloe

This is fixing some outdated links, found with [deadlink](https://github.com/nschloe/deadlink).
```
deadlink check README.md
```

2021-12-06 22:47 UTC, gokaygurcan requested changes

2021-12-06 22:47 UTC, gokaygurcan commented on README.md
> +* [react](http://reactjs.org/) - A library for building user interfaces. It's declarative, efficient, and extremely flexible. Works with a Virtual DOM.
Why not https here?

2021-12-06 22:47 UTC, gokaygurcan commented on README.md
> -* [Beautiful docs](http://beautifuldocs.com/) is a documentation viewer based on markdown files.
Nice one.

2021-12-06 22:48 UTC, gokaygurcan commented
I wouldn't call them _dead_ except for a few. But this is a nice update, thanks.

2021-12-06 23:46 UTC, nschloe commented on README.md
> +* [react](http://reactjs.org/) - A library for building user interfaces. It's declarative, efficient, and extremely flexible. Works with a Virtual DOM.
Fixed that.

2021-12-06 23:49 UTC, nschloe commented
> I don't know about deadlink but probably it does the same thing with different name.

Probably yeah. deadlink has the option of rewriting 301s and 308s ("permantent direct").

2021-12-07 10:57 UTC, gokaygurcan approved these changes

2021-12-07 10:58 UTC, Ashe-reset commented
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

2021-12-07 10:58 UTC, kitety commented
您好，您的邮件已经收到。

2021-12-07 11:08 UTC, gokaygurcan commented
Looks good, thanks again.

2021-12-07 11:08 UTC, merged